version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/dodo
    overwrite: yes

permissions:
  - object: /
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      timeout: 60
  AfterInstall:
    - location: scripts/start.sh
      timeout: 60