spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:mem:tes;MODE=PostgreSQL;NON_KEYWORDS=USER
    username: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true

  output:
    ansi:
      enabled: always

  profiles:
    include: private


env:
  JWT_SECRET: ${{secrets.JWT_SECRET}}
  ACCESS_KEY: ${{secrets.AWS_S3_ACCESS_KEY}}
  SECRET_KEY: ${{secrets.AWS_S3_SECRET_KEY}}
  S3_BUCKET: ${{AWS_S3_BUCKET}}


authentication:
  access-token:
    secretKey: ${JWT_SECRET}


#server:
#  error:
#    include-message: always

